# Generated by Django 3.0.7 on 2024-03-25 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_alter_voter_lgu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='cat',
            field=models.CharField(choices=[('National', 'National'), ('LGU', 'LGU')], max_length=10),
        ),
        migrations.AlterField(
            model_name='voter',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
